version: '3.8'

services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-document-qa
    ports:
      - "5000:5000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-gemini}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - DEBUG=${DEBUG:-False}
      - UPLOAD_FOLDER=/app/data/uploads
      - VECTOR_DB_PATH=/app/data/vector_db
      - DATABASE_URL=sqlite:////app/data/metadata/documents.db
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - MAX_DOCUMENTS=${MAX_DOCUMENTS:-20}
      - MAX_PAGES_PER_DOCUMENT=${MAX_PAGES_PER_DOCUMENT:-1000}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-1000}
      - TOP_K_RESULTS=${TOP_K_RESULTS:-5}
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/vector_db:/app/data/vector_db
      - ./data/metadata:/app/data/metadata
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  uploads:
  vector_db:
  metadata: